spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dulaty_queue_db
    username: postgres
    password: QBxrJxlYbwWELoR2YLAfGxZxBy8GS
  task:
    execution:
      pool:
        core-size: 16
        max-size: 64
        queue-capacity: 5000

server:
  tomcat:
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    accept-count: 200
    connection-timeout: 20000
