spring:
  profiles:
    active: prod
  application:
    name: dulaty-queue
  liquibase:
    database-change-log-lock-table: dulaty_queue_sys_db_change_log_lock
    database-change-log-table: dulaty_queue_sys_db_change_log
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: mail.dulaty.kz
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/mail-templates/
    charset: UTF-8
    cache: false
springdoc:
  swagger-ui:
    docExpansion: none
dulaty:
  scheduling:
    ticket-cleaner: "0 0 0 * * *" # Удаление номера тикетов каждый день в полночь
  queue:
    jwt:
      secret: 9586f460d415c152be0435180a3aeef07b6af2e155373d9f1d5c8a76abde1c38
      expiration: 43200000
  mail-properties:
    domain: http://localhost:8080
    email-confirmation-link-pattern: http://localhost:8080/api/v1/auth/confirm-email?token=%s
    reset-password-link-pattern: http://localhost:8080/api/v1/auth/reset-password/%s
